# Generated by Django 6.0.3 on 2026-03-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration_hours',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
