# Generated by Django 6.0.3 on 2026-03-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_duration_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='platform_fee_percent',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
