# Generated by Django 6.0.3 on 2026-03-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_capacity_tickettype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='price',
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], db_index=True, default='OFFLINE', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='online_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
