# Generated by Django 6.0.3 on 2026-03-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='platform_fee_percent',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=5),
        ),
    ]
