# Generated by Django 6.0.3 on 2026-03-14 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        ('tickets', '0002_order_event_order_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketplacelisting',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='marketplacelisting',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='marketplacelisting',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SOLD', 'Sold'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='marketplacelisting',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='tickets.ticket'),
        ),
    ]
